# Generated by Django 5.1.7 on 2025-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_original_text_alter_message_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='original_text',
        ),
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000000000),
        ),
    ]
